baseURL: https://calvinegs.github.io/
languageCode: en-us
title: 永誌不忘 • 筆記簿
paginate: 5
theme: hugo-PaperMod

disqusShortname: calvinegs-github-io

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Theme PaperMod
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  comments: true
  images: ["papermod-cover.png"]

  profileMode:
    enabled: false
    # title: Peace, Health, Happiness, Joy
    title: 平安 健康 幸福 快樂
    imageUrl: "https://user-images.githubusercontent.com/21993717/129662156-6b25c774-2c8d-461f-acf8-e43e139d1d16.png"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "寫筆記"
    Content: >

      - 有些事想要**遺忘** • 有些事必須**記得**

      - 不想忘的事 簡單 寫下就好 • 不想記得的 卻*怪難的*!

      - 這是我的筆記本，把學習中和實作過的紀錄下來，**幫助自己**也幫助別人（希望可以）。

  # socialIcons:
  #     - name: github
  #       url: "https://github.com/adityatelange/hugo-PaperMod"
  #     - name: KoFi
  #       url: "https://ko-fi.com/adityatelange"
  #     - name: RsS
  #       url: "index.xml"

  editPost:
    URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 5
    - identifier: archives
      name: archives
      url: /archives/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 25
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
